import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
        <div>
            <a href="/" className="text-2xl">Navbar</a>
        </div>

        <div className="flex gap-5 justify-center">
            <a href="/about" className="text-xl">About</a>
            <a href="/profile" className="text-xl">Profile</a>
        </div>
        {children}
      </body>
    </html>
  );
}
